### ISSUE TITLE
libmini_racer.glibc.so: cannot open shared object file: No such file or directory in RHEL

### ISSUE THREAD

**Issue by poovannan89** [sqreen/PyMiniRacer#140]
### Steps to reproduce
Installed py-mini-racer via pip3 on RHEL 8.3 for using in Mistral (openstack project).

### Expected behavior
py_mini_racer works fine for javascript snippets.

### Actual behavior
After install, file libmini_racer.glibc.so was missing. So, copied it from whl file. After that also 
cannot open error occurs even though file exists : 

>>> from py_mini_racer import py_mini_racer
>>> ctx = py_mini_racer.MiniRacer()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/py_mini_racer/py_mini_racer.py", line 168, in __init__
    self.ext = _fetch_ext_handle()
  File "/usr/local/lib/python3.6/site-packages/py_mini_racer/py_mini_racer.py", line 124, in _fetch_ext_handle
    _ext_handle = ctypes.CDLL(EXTENSION_PATH)
  File "/usr/lib64/python3.6/ctypes/__init__.py", line 343, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/python3.6/site-packages/py_mini_racer/libmini_racer.glibc.so: cannot open shared object file: No such file or directory

Query : Is py_mini_racer compatibile for RHEL ?

### System configuration
RHEL 8.3
**PyMiniRacer version**:
0.5.0
**Python version**:
3.6.8

**Comment by nizox** [comment]
Can you please copy the result of the following command:
```
ldd usr/local/lib/python3.6/site-packages/py_mini_racer/libmini_racer.glibc.so
```

I quickly tried installing and running PyMiniRacer on Centos 8.3 with Python 3.6 without issues as you can see below:
```
$ docker run --rm -ti centos:8.3.2011
[root@308e19648078 /]# dnf install python36
[...]
Installed:
  platform-python-pip-9.0.3-18.el8.noarch           python3-pip-9.0.3-18.el8.noarch           python3-setuptools-39.2.0-6.el8.noarch           python36-3.6.8-2.module_el8.3.0+562+e162826a.x86_64

Complete!
[root@308e19648078 /]# pip3 install py-mini-racer
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Collecting py-mini-racer
  Downloading https://files.pythonhosted.org/packages/f4/55/8a55987cfd7e55807ec7c7424abbdaae66de9c1d2385a9ebff81ef829dc1/py_mini_racer-0.5.0-py2.py3-none-manylinux1_x86_64.whl (5.3MB)
    100% |████████████████████████████████| 5.4MB 248kB/s
Installing collected packages: py-mini-racer
Successfully installed py-mini-racer-0.5.0
[root@308e19648078 /]# python3
Python 3.6.8 (default, Aug 24 2020, 17:57:11)
[GCC 8.3.1 20191121 (Red Hat 8.3.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from py_mini_racer import py_mini_racer
>>> ctx = py_mini_racer.MiniRacer()
>>> ctx.eval('1+1')
2
>>>
[root@308e19648078 /]#
```

**Comment by poovannan89** [comment]
Hi, Thanks for quick response. Here is the output : 

[root@os4p70 ~]# ldd /usr/local/lib/python3.6/site-packages/py_mini_racer/libmini_racer.glibc.so
        not a dynamic executable

[root@os4p70 ~]# ls -ltr /usr/local/lib/python3.6/site-packages/py_mini_racer/libmini_racer.glibc.so
-rwxr-xr-x. 1 root root 16590912 Apr  6 01:12 /usr/local/lib/python3.6/site-packages/py_mini_racer/libmini_racer.glibc.so

**Comment by poovannan89** [comment]
I checked further on another machine. RHEL 8.2. There is no issue and it works fine. 
Suspect some install issue on 8.3. Will reinstall the package and try.
