### ISSUE TITLE
MiniRacer.execute failure

### ISSUE THREAD

**Issue by SeaHOH** [sqreen/PyMiniRacer#148]
### Steps to reproduce
```python
Python 3.10.1 (tags/v3.10.1:2cd268a, Dec  6 2021, 19:10:37) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from py_mini_racer import MiniRacer
>>> ctx = MiniRacer()
>>> ctx.eval('var a = 1')
>>>
>>> ctx.execute('var b = 1')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "M:\site-packages\py_mini_racer\py_mini_racer.py", line 235, in execute
    ret = self.eval(wrapped_expr, timeout=timeout, max_memory=max_memory)
  File "M:\site-packages\py_mini_racer\py_mini_racer.py", line 221, in eval
    return MiniRacerValue(self, res).to_python()
  File "M:\site-packages\py_mini_racer\py_mini_racer.py", line 403, in to_python
    self._raise_from_error()
  File "M:\site-packages\py_mini_racer\py_mini_racer.py", line 391, in _raise_from_error
    raise JSParseException(msg)
py_mini_racer.py_mini_racer.JSParseException: b'Unknown JavaScript error during parse'
>>>
>>> ctx.eval('''
...     function foo() {
...         return 1
...     }
...     foo()''')
1
>>>
>>> ctx.execute('''
...     function bar() {
...         return 1
...     }
...     bar()''')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "M:\site-packages\py_mini_racer\py_mini_racer.py", line 235, in execute
    ret = self.eval(wrapped_expr, timeout=timeout, max_memory=max_memory)
  File "M:\site-packages\py_mini_racer\py_mini_racer.py", line 221, in eval
    return MiniRacerValue(self, res).to_python()
  File "M:\site-packages\py_mini_racer\py_mini_racer.py", line 403, in to_python
    self._raise_from_error()
  File "M:\site-packages\py_mini_racer\py_mini_racer.py", line 391, in _raise_from_error
    raise JSParseException(msg)
py_mini_racer.py_mini_racer.JSParseException: b'Unknown JavaScript error during parse'
>>>
```

### Expected behavior
All expressions can be evaluated via `MiniRacer.execute` as same as `MiniRacer.eval`.

### Actual behavior
Some expressions can not be evaluated via `MiniRacer.execute`.

### System configuration
**PyMiniRacer version**:
0.6.0 win_amd64

**Python version**:
3.10.1

**Comment by SeaHOH** [comment]
I had tried use `eval` to instead of `function`, it works. But new issue occurd, the scope has been limited.

**Comment by SeaHOH** [comment]
Hmm... is there it possible to add a function likes `res = ext.mr_json_stringify(res)`, intead of the wrapped expression string?

**Comment by SeaHOH** [comment]
I have used esprima to skip this issue.
https://github.com/SeaHOH/jsengine/commit/5ebe633bc09bb5adb7b391778111b37978abc351

**Comment by bpcreech** [comment]
After discussion with the owners, I've forked PyMiniRacer into https://github.com/bpcreech/PyMiniRacer.

It lives on PyPI at https://pypi.org/project/mini-racer/ (note, dropping `py-` from `py-mini-racer`).

So, fwiw, while this still doesn't work on `mini-racer` I at least improved the parse error. :D

Running on https://colab.research.google.com:
```
!pip install mini-racer

from py_mini_racer import MiniRacer
mr = MiniRacer()
mr.execute('var b = 1')

---------------------------------------------------------------------------
JSParseException                          Traceback (most recent call last)
[<ipython-input-7-5d6307537a63>](https://localhost:8080/#) in <cell line: 3>()
      1 from py_mini_racer import MiniRacer
      2 mr = MiniRacer()
----> 3 mr.execute('var b = 1')

3 frames
[/usr/local/lib/python3.10/dist-packages/py_mini_racer/py_mini_racer.py](https://localhost:8080/#) in _raise_from_error(self)
    517         klass, generic_msg = error_info
    518 
--> 519         raise klass(self._get_exception_msg() or generic_msg)
    520 
    521     def to_python(self) -> Any:

JSParseException: SyntaxError: Unexpected token 'var'
```

**Comment by bpcreech** [comment]
@SeaHOH I know it's been a long time, but just out of curiosity, if what you want is a JSON output, could you do:

```python
ctx.eval("""
    // code here... which fills in a variable let's say called "ret"...
    // then finally:
    JSON.stringify(ret);
""") 
```

That is to say, while `ctx.execute` is problematic in its construction, I don't think we need to expose a `res = ext.mr_json_stringify(ctx, res)`, one can instead tag that onto the end of the `eval`, right?

My inclination is to suggest that and *deprecate* `ctx.execute` because it seems impossible to fix without creating a breaking change.
