### ISSUE TITLE
pip install fails on Windows

### ISSUE THREAD

**Issue by bowbahdoe** [sqreen/PyMiniRacer#29]
### Steps to reproduce
pip install py_mini_racer
### Expected behavior
I expect the install to work without crashing
### Actual behavior
The setup fails on install with the following stacktrace

```
(venv) C:\Users\Ethan\Development\pyminiracer>pip install py_mini_racer
Collecting py_mini_racer
  Downloading py_mini_racer-0.1.10.tar.gz (326kB)
    100% |████████████████████████████████| 327kB 889kB/s
Collecting enum34 (from py_mini_racer)
  Downloading enum34-1.1.6-py3-none-any.whl
Building wheels for collected packages: py-mini-racer
  Running setup.py bdist_wheel for py-mini-racer ... error
  Complete output from command c:\users\ethan\development\pyminiracer\venv\scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Ethan\\AppData\\Local\\Temp\\pip-build-k_0v62yn\\py-mini-racer\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\Ethan\AppData\Local\Temp\tmpk011rv_ppip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\py_mini_racer
  copying py_mini_racer\py_mini_racer.py -> build\lib.win-amd64-3.6\py_mini_racer
  copying py_mini_racer\__init__.py -> build\lib.win-amd64-3.6\py_mini_racer
  creating build\lib.win-amd64-3.6\py_mini_racer\extension
  copying py_mini_racer\extension\v8_build.py -> build\lib.win-amd64-3.6\py_mini_racer\extension
  copying py_mini_racer\extension\__init__.py -> build\lib.win-amd64-3.6\py_mini_racer\extension
  running egg_info
  writing py_mini_racer.egg-info\PKG-INFO
  writing dependency_links to py_mini_racer.egg-info\dependency_links.txt
  writing requirements to py_mini_racer.egg-info\requires.txt
  writing top-level names to py_mini_racer.egg-info\top_level.txt
  reading manifest file 'py_mini_racer.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files matching '__pycache__' found under directory '*'
  warning: no previously-included files matching '*.py[co]' found under directory '*'
  writing manifest file 'py_mini_racer.egg-info\SOURCES.txt'
  copying py_mini_racer\extension\mini_racer_extension.cc -> build\lib.win-amd64-3.6\py_mini_racer\extension
  running build_ext
  running build_v8
  cloning depot tools submodule
  Initialized empty Git repository in C:/Users/Ethan/AppData/Local/Temp/pip-build-k_0v62yn/py-mini-racer/.git/
  Cloning into 'vendor/depot_tools'...
  building v8
  DEBUG:py_mini_racer.extension.v8_build:Calling: 'fetch v8' from working directory C:\Users\Ethan\AppData\Local\Temp\pip-build-k_0v62yn\py-mini-racer\py_mini_racer\extension\v8
  'fetch' is not recognized as an internal or external command,
  operable program or batch file.
  Traceback (most recent call last):
    File "C:\Users\Ethan\AppData\Local\Temp\pip-build-k_0v62yn\py-mini-racer\setup.py", line 139, in build_extension
      self.run_command('build_v8')
    File "c:\users\ethan\anaconda3\Lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\ethan\anaconda3\Lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Users\Ethan\AppData\Local\Temp\pip-build-k_0v62yn\py-mini-racer\setup.py", line 179, in run
      build_v8(target)
    File "C:\Users\Ethan\AppData\Local\Temp\pip-build-k_0v62yn\py-mini-racer\py_mini_racer\extension\v8_build.py", line 162, in build_v8
      ensure_v8_src()
    File "C:\Users\Ethan\AppData\Local\Temp\pip-build-k_0v62yn\py-mini-racer\py_mini_racer\extension\v8_build.py", line 61, in ensure_v8_src
      fetch_v8(path)
    File "C:\Users\Ethan\AppData\Local\Temp\pip-build-k_0v62yn\py-mini-racer\py_mini_racer\extension\v8_build.py", line 73, in fetch_v8
      call("fetch v8")
    File "C:\Users\Ethan\AppData\Local\Temp\pip-build-k_0v62yn\py-mini-racer\py_mini_racer\extension\v8_build.py", line 36, in call
      return subprocess.check_call(cmd, shell=True, env=current_env)
    File "c:\users\ethan\anaconda3\Lib\subprocess.py", line 291, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command 'fetch v8' returned non-zero exit status 1.

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\Ethan\AppData\Local\Temp\pip-build-k_0v62yn\py-mini-racer\setup.py", line 220, in <module>
      'build_v8': MiniRacerBuildV8
    File "c:\users\ethan\anaconda3\Lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "c:\users\ethan\anaconda3\Lib\distutils\dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "c:\users\ethan\anaconda3\Lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "c:\users\ethan\development\pyminiracer\venv\lib\site-packages\wheel\bdist_wheel.py", line 179, in run
      self.run_command('build')
    File "c:\users\ethan\anaconda3\Lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\ethan\anaconda3\Lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "c:\users\ethan\anaconda3\Lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "c:\users\ethan\anaconda3\Lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\ethan\anaconda3\Lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "c:\users\ethan\development\pyminiracer\venv\lib\site-packages\setuptools\command\build_ext.py", line 75, in run
      _build_ext.run(self)
    File "c:\users\ethan\anaconda3\Lib\distutils\command\build_ext.py", line 339, in run
      self.build_extensions()
    File "c:\users\ethan\anaconda3\Lib\distutils\command\build_ext.py", line 448, in build_extensions
      self._build_extensions_serial()
    File "c:\users\ethan\anaconda3\Lib\distutils\command\build_ext.py", line 473, in _build_extensions_serial
      self.build_extension(ext)
    File "C:\Users\Ethan\AppData\Local\Temp\pip-build-k_0v62yn\py-mini-racer\setup.py", line 152, in build_extension
      raise Exception(err_msg % repr(e))
  Exception: py_mini_racer failed to build, ensure you have an up-to-date pip (>= 8.1) to use the wheel instead
              To update pip: 'pip install -U pip'
              See also: https://github.com/sqreen/PyMiniRacer#binary-builds-availability

              Original error: CalledProcessError(1, 'fetch v8')

  ----------------------------------------
  Failed building wheel for py-mini-racer
  Running setup.py clean for py-mini-racer
Failed to build py-mini-racer
Installing collected packages: enum34, py-mini-racer
  Running setup.py install for py-mini-racer ... error
    Complete output from command c:\users\ethan\development\pyminiracer\venv\scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Ethan\\AppData\\Local\\Temp\\pip-build-k_0v62yn\\py-mini-racer\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Ethan\AppData\Local\Temp\pip-jn5_2syv-record\install-record.txt --single-version-externally-managed --compile --install-headers c:\users\ethan\development\pyminiracer\venv\include\site\python3.6\py-mini-racer:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\py_mini_racer
    copying py_mini_racer\py_mini_racer.py -> build\lib.win-amd64-3.6\py_mini_racer
    copying py_mini_racer\__init__.py -> build\lib.win-amd64-3.6\py_mini_racer
    creating build\lib.win-amd64-3.6\py_mini_racer\extension
    copying py_mini_racer\extension\v8_build.py -> build\lib.win-amd64-3.6\py_mini_racer\extension
    copying py_mini_racer\extension\__init__.py -> build\lib.win-amd64-3.6\py_mini_racer\extension
    running egg_info
    writing py_mini_racer.egg-info\PKG-INFO
    writing dependency_links to py_mini_racer.egg-info\dependency_links.txt
    writing requirements to py_mini_racer.egg-info\requires.txt
    writing top-level names to py_mini_racer.egg-info\top_level.txt
    reading manifest file 'py_mini_racer.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '__pycache__' found under directory '*'
    warning: no previously-included files matching '*.py[co]' found under directory '*'
    writing manifest file 'py_mini_racer.egg-info\SOURCES.txt'
    copying py_mini_racer\extension\mini_racer_extension.cc -> build\lib.win-amd64-3.6\py_mini_racer\extension
    running build_ext
    running build_v8
    building v8
    DEBUG:py_mini_racer.extension.v8_build:Calling: 'gclient fetch' from working directory C:\Users\Ethan\AppData\Local\Temp\pip-build-k_0v62yn\py-mini-racer\py_mini_racer\extension\v8
    'gclient' is not recognized as an internal or external command,
    operable program or batch file.
    Traceback (most recent call last):
      File "C:\Users\Ethan\AppData\Local\Temp\pip-build-k_0v62yn\py-mini-racer\setup.py", line 139, in build_extension
        self.run_command('build_v8')
      File "c:\users\ethan\anaconda3\Lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\ethan\anaconda3\Lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\Ethan\AppData\Local\Temp\pip-build-k_0v62yn\py-mini-racer\setup.py", line 179, in run
        build_v8(target)
      File "C:\Users\Ethan\AppData\Local\Temp\pip-build-k_0v62yn\py-mini-racer\py_mini_racer\extension\v8_build.py", line 162, in build_v8
        ensure_v8_src()
      File "C:\Users\Ethan\AppData\Local\Temp\pip-build-k_0v62yn\py-mini-racer\py_mini_racer\extension\v8_build.py", line 63, in ensure_v8_src
        update_v8(path)
      File "C:\Users\Ethan\AppData\Local\Temp\pip-build-k_0v62yn\py-mini-racer\py_mini_racer\extension\v8_build.py", line 80, in update_v8
        call("gclient fetch")
      File "C:\Users\Ethan\AppData\Local\Temp\pip-build-k_0v62yn\py-mini-racer\py_mini_racer\extension\v8_build.py", line 36, in call
        return subprocess.check_call(cmd, shell=True, env=current_env)
      File "c:\users\ethan\anaconda3\Lib\subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command 'gclient fetch' returned non-zero exit status 1.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Ethan\AppData\Local\Temp\pip-build-k_0v62yn\py-mini-racer\setup.py", line 220, in <module>
        'build_v8': MiniRacerBuildV8
      File "c:\users\ethan\anaconda3\Lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\ethan\anaconda3\Lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "c:\users\ethan\anaconda3\Lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\ethan\development\pyminiracer\venv\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\users\ethan\anaconda3\Lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "c:\users\ethan\anaconda3\Lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\ethan\anaconda3\Lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\ethan\anaconda3\Lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "c:\users\ethan\anaconda3\Lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\ethan\anaconda3\Lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\ethan\development\pyminiracer\venv\lib\site-packages\setuptools\command\build_ext.py", line 75, in run
        _build_ext.run(self)
      File "c:\users\ethan\anaconda3\Lib\distutils\command\build_ext.py", line 339, in run
        self.build_extensions()
      File "c:\users\ethan\anaconda3\Lib\distutils\command\build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "c:\users\ethan\anaconda3\Lib\distutils\command\build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "C:\Users\Ethan\AppData\Local\Temp\pip-build-k_0v62yn\py-mini-racer\setup.py", line 152, in build_extension
        raise Exception(err_msg % repr(e))
    Exception: py_mini_racer failed to build, ensure you have an up-to-date pip (>= 8.1) to use the wheel instead
                To update pip: 'pip install -U pip'
                See also: https://github.com/sqreen/PyMiniRacer#binary-builds-availability

                Original error: CalledProcessError(1, 'gclient fetch')

    ----------------------------------------
Command "c:\users\ethan\development\pyminiracer\venv\scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Ethan\\AppData\\Local\\Temp\\pip-build-k_0v62yn\\py-mini-racer\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Ethan\AppData\Local\Temp\pip-jn5_2syv-record\install-record.txt --single-version-externally-managed --compile --install-headers c:\users\ethan\development\pyminiracer\venv\include\site\python3.6\py-mini-racer" failed with error code 1 in C:\Users\Ethan\AppData\Local\Temp\pip-build-k_0v62yn\py-mini-racer\
```

### System configuration
**PyMiniRacer version**: 0.1.10
**pip version**: 9.0.1

**Python version**: Anaconda 3.6

**Comment by aviat** [comment]
@bowbahdoe would you be interested in proposing an AppVeyor build for PyMiniRacer? I would be happy to integrate this.

**Comment by kokhoor** [comment]
Is it possible to install PyMiniRacer in Windows?

**Comment by bowbahdoe** [comment]
As far as I can tell it's just a build issue, not any apparent incompatibility. I'm working on a fix as @aviat suggested, but Im figuring it out as I go, so it might be awhile before a pull

**Comment by aviat** [comment]
I'll be happy to help, would you have any question.

**Comment by kokhoor** [comment]
Is there any simpler workaround at the moment, for example instructions to get it work with a v8 dll

**Comment by aviat** [comment]
We don’t have this at the moment, I’ll be happy to welcome any pull request on this!

**Comment by Congee** [comment]
`fetch v8` fails on my Linux box, too.
What is `fetch`? Are you using FreeBSD?
