### ISSUE TITLE
Invalid code throws "Unknown JavaScript error during parse" instead of a SyntaxError

### ISSUE THREAD

**Issue by ThomasHickman** [sqreen/PyMiniRacer#42]
With the script:
```
from py_mini_racer import py_mini_racer

ctx = py_mini_racer.MiniRacer()
ctx.eval("+")
```
The exception:
```
Traceback (most recent call last):
  File "test_racer.py", line 4, in <module>
    ctx.eval("+")
  File ".../py_mini_racer/py_mini_racer.py", line 125, in eval
    python_value = res.contents.to_python()
  File ".../py_mini_racer/py_mini_racer.py", line 224, in to_python
    raise JSParseException(msg)
py_mini_racer.py_mini_racer.JSParseException: b'Unknown JavaScript error during parse'
```

This should give an SyntaxError, as shown in `node.js`:
```
$ node --eval +
[eval]:1
+
^

SyntaxError: Unexpected end of input
    at new Script (vm.js:51:7)
    at createScript (vm.js:138:10)
    at Object.runInThisContext (vm.js:199:10)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:660:30)
    at evalScript (bootstrap_node.js:474:27)
    at startup (bootstrap_node.js:169:9)
    at bootstrap_node.js:617:3
```

### System configuration
**PyMiniRacer version**: 0.1.12

**Python version**: 3.6.4

**Comment by aviat** [comment]
Hey @ThomasHickman thanks a lot for your report.

This is completely valid!

Feel free to open a Pull Request to help us with this (the skiped Python unit test could be a first step!).
Else this may be scheduled in a later release.

**Comment by mcdoker18** [comment]
@aviat Hi! Sorry, I forgot to add the keyword "closes" to MR. Can you close the issue?
