### ISSUE TITLE
Pip install ERROR on Windows

### ISSUE THREAD

**Issue by jaredliw** [sqreen/PyMiniRacer#92]
I have upgrade setuptools and pip but I still can't install py-mini-racer. 
Please help me. Thanks! :p
### Actual behaviour

(base) C:\Users\jared>pip install py-mini-racer
Collecting py-mini-racer
  Using cached https://files.pythonhosted.org/packages/25/79/e158bbf5a2bbcdf990738566653d8caa8bc612007d4c0ed319bb3803a832/py_mini_racer-0.1.18.tar.gz
Building wheels for collected packages: py-mini-racer
  Building wheel for py-mini-racer (setup.py) ... error
  ERROR: Complete output from command 'C:\Users\jared\Anaconda3\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\jared\\AppData\\Local\\Temp\\pip-install-bht625n2\\py-mini-racer\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\jared\AppData\Local\Temp\pip-wheel-m5u8p29q' --python-tag cp37:
  ERROR: running bdist_wheel
  The [wheel] section is deprecated. Use [bdist_wheel] instead.
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\py_mini_racer
  copying py_mini_racer\py_mini_racer.py -> build\lib.win-amd64-3.7\py_mini_racer
  copying py_mini_racer\__init__.py -> build\lib.win-amd64-3.7\py_mini_racer
  creating build\lib.win-amd64-3.7\py_mini_racer\extension
  copying py_mini_racer\extension\v8_build.py -> build\lib.win-amd64-3.7\py_mini_racer\extension
  copying py_mini_racer\extension\__init__.py -> build\lib.win-amd64-3.7\py_mini_racer\extension
  running egg_info
  writing py_mini_racer.egg-info\PKG-INFO
  writing dependency_links to py_mini_racer.egg-info\dependency_links.txt
  writing top-level names to py_mini_racer.egg-info\top_level.txt
  reading manifest file 'py_mini_racer.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files matching '__pycache__' found under directory '*'
  warning: no previously-included files matching '*.py[co]' found under directory '*'
  writing manifest file 'py_mini_racer.egg-info\SOURCES.txt'
  copying py_mini_racer\extension\mini_racer_extension.cc -> build\lib.win-amd64-3.7\py_mini_racer\extension
  running build_ext
  running build_v8
  Initialized empty Git repository in C:/Users/jared/AppData/Local/Temp/pip-install-bht625n2/py-mini-racer/.git/
  Cloning into 'vendor/depot_tools'...
  Updating files: 100% (675/675), done.
  DEBUG:py_mini_racer.extension.v8_build:Calling: 'fetch v8' from working directory C:\Users\jared\AppData\Local\Temp\pip-install-bht625n2\py-mini-racer\py_mini_racer\extension\v8
  'fetch' is not recognized as an internal or external command,
  operable program or batch file.
  Traceback (most recent call last):
    File "C:\Users\jared\AppData\Local\Temp\pip-install-bht625n2\py-mini-racer\setup.py", line 161, in build_extension
      self.run_command('build_v8')
    File "C:\Users\jared\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\jared\Anaconda3\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\jared\AppData\Local\Temp\pip-install-bht625n2\py-mini-racer\setup.py", line 208, in run
      build_v8()
    File "C:\Users\jared\AppData\Local\Temp\pip-install-bht625n2\py-mini-racer\py_mini_racer\extension\v8_build.py", line 179, in build_v8
      ensure_v8_src()
    File "C:\Users\jared\AppData\Local\Temp\pip-install-bht625n2\py-mini-racer\py_mini_racer\extension\v8_build.py", line 63, in ensure_v8_src
      fetch_v8(path)
    File "C:\Users\jared\AppData\Local\Temp\pip-install-bht625n2\py-mini-racer\py_mini_racer\extension\v8_build.py", line 75, in fetch_v8
      call("fetch v8")
    File "C:\Users\jared\AppData\Local\Temp\pip-install-bht625n2\py-mini-racer\py_mini_racer\extension\v8_build.py", line 38, in call
      return subprocess.check_call(cmd, shell=True, env=current_env)
    File "C:\Users\jared\Anaconda3\lib\subprocess.py", line 347, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command 'fetch v8' returned non-zero exit status 1.
  Traceback (most recent call last):
    File "C:\Users\jared\AppData\Local\Temp\pip-install-bht625n2\py-mini-racer\setup.py", line 161, in build_extension
      self.run_command('build_v8')
    File "C:\Users\jared\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\jared\Anaconda3\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\jared\AppData\Local\Temp\pip-install-bht625n2\py-mini-racer\setup.py", line 208, in run
      build_v8()
    File "C:\Users\jared\AppData\Local\Temp\pip-install-bht625n2\py-mini-racer\py_mini_racer\extension\v8_build.py", line 179, in build_v8
      ensure_v8_src()
    File "C:\Users\jared\AppData\Local\Temp\pip-install-bht625n2\py-mini-racer\py_mini_racer\extension\v8_build.py", line 63, in ensure_v8_src
      fetch_v8(path)
    File "C:\Users\jared\AppData\Local\Temp\pip-install-bht625n2\py-mini-racer\py_mini_racer\extension\v8_build.py", line 75, in fetch_v8
      call("fetch v8")
    File "C:\Users\jared\AppData\Local\Temp\pip-install-bht625n2\py-mini-racer\py_mini_racer\extension\v8_build.py", line 38, in call
      return subprocess.check_call(cmd, shell=True, env=current_env)
    File "C:\Users\jared\Anaconda3\lib\subprocess.py", line 347, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command 'fetch v8' returned non-zero exit status 1.

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\jared\AppData\Local\Temp\pip-install-bht625n2\py-mini-racer\setup.py", line 250, in <module>
      'build_v8': MiniRacerBuildV8,
    File "C:\Users\jared\Anaconda3\lib\site-packages\setuptools\__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\jared\Anaconda3\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Users\jared\Anaconda3\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "C:\Users\jared\Anaconda3\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\jared\Anaconda3\lib\site-packages\wheel\bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "C:\Users\jared\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\jared\Anaconda3\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\jared\Anaconda3\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\Users\jared\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\jared\Anaconda3\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\jared\Anaconda3\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
      _build_ext.run(self)
    File "C:\Users\jared\Anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
      _build_ext.build_ext.run(self)
    File "C:\Users\jared\Anaconda3\lib\distutils\command\build_ext.py", line 340, in run
      self.build_extensions()
    File "C:\Users\jared\Anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 194, in build_extensions
      self.build_extension(ext)
    File "C:\Users\jared\AppData\Local\Temp\pip-install-bht625n2\py-mini-racer\setup.py", line 180, in build_extension
      raise Exception(err_msg % repr(e))
  Exception: py_mini_racer failed to build, ensure you have an up-to-date pip (>= 8.1) to use the wheel instead
              To update pip: 'pip install -U pip'
              See also: https://github.com/sqreen/PyMiniRacer#binary-builds-availability

              Original error: CalledProcessError(1, 'fetch v8')
  cloning depot tools submodule
  building v8
  ----------------------------------------
  ERROR: Failed building wheel for py-mini-racer
  Running setup.py clean for py-mini-racer
Failed to build py-mini-racer
Installing collected packages: py-mini-racer
  Running setup.py install for py-mini-racer ... error
    ERROR: Complete output from command 'C:\Users\jared\Anaconda3\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\jared\\AppData\\Local\\Temp\\pip-install-bht625n2\\py-mini-racer\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\jared\AppData\Local\Temp\pip-record-bfc_szuj\install-record.txt' --single-version-externally-managed --compile:
    ERROR: running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\py_mini_racer
    copying py_mini_racer\py_mini_racer.py -> build\lib.win-amd64-3.7\py_mini_racer
    copying py_mini_racer\__init__.py -> build\lib.win-amd64-3.7\py_mini_racer
    creating build\lib.win-amd64-3.7\py_mini_racer\extension
    copying py_mini_racer\extension\v8_build.py -> build\lib.win-amd64-3.7\py_mini_racer\extension
    copying py_mini_racer\extension\__init__.py -> build\lib.win-amd64-3.7\py_mini_racer\extension
    running egg_info
    writing py_mini_racer.egg-info\PKG-INFO
    writing dependency_links to py_mini_racer.egg-info\dependency_links.txt
    writing top-level names to py_mini_racer.egg-info\top_level.txt
    reading manifest file 'py_mini_racer.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '__pycache__' found under directory '*'
    warning: no previously-included files matching '*.py[co]' found under directory '*'
    writing manifest file 'py_mini_racer.egg-info\SOURCES.txt'
    copying py_mini_racer\extension\mini_racer_extension.cc -> build\lib.win-amd64-3.7\py_mini_racer\extension
    running build_ext
    running build_v8
    DEBUG:py_mini_racer.extension.v8_build:Calling: 'gclient fetch' from working directory C:\Users\jared\AppData\Local\Temp\pip-install-bht625n2\py-mini-racer\py_mini_racer\extension\v8
    'gclient' is not recognized as an internal or external command,
    operable program or batch file.
    Traceback (most recent call last):
      File "C:\Users\jared\AppData\Local\Temp\pip-install-bht625n2\py-mini-racer\setup.py", line 161, in build_extension
        self.run_command('build_v8')
      File "C:\Users\jared\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\jared\Anaconda3\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\jared\AppData\Local\Temp\pip-install-bht625n2\py-mini-racer\setup.py", line 208, in run
        build_v8()
      File "C:\Users\jared\AppData\Local\Temp\pip-install-bht625n2\py-mini-racer\py_mini_racer\extension\v8_build.py", line 179, in build_v8
        ensure_v8_src()
      File "C:\Users\jared\AppData\Local\Temp\pip-install-bht625n2\py-mini-racer\py_mini_racer\extension\v8_build.py", line 65, in ensure_v8_src
        update_v8(path)
      File "C:\Users\jared\AppData\Local\Temp\pip-install-bht625n2\py-mini-racer\py_mini_racer\extension\v8_build.py", line 82, in update_v8
        call("gclient fetch")
      File "C:\Users\jared\AppData\Local\Temp\pip-install-bht625n2\py-mini-racer\py_mini_racer\extension\v8_build.py", line 38, in call
        return subprocess.check_call(cmd, shell=True, env=current_env)
      File "C:\Users\jared\Anaconda3\lib\subprocess.py", line 347, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command 'gclient fetch' returned non-zero exit status 1.
    Traceback (most recent call last):
      File "C:\Users\jared\AppData\Local\Temp\pip-install-bht625n2\py-mini-racer\setup.py", line 161, in build_extension
        self.run_command('build_v8')
      File "C:\Users\jared\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\jared\Anaconda3\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\jared\AppData\Local\Temp\pip-install-bht625n2\py-mini-racer\setup.py", line 208, in run
        build_v8()
      File "C:\Users\jared\AppData\Local\Temp\pip-install-bht625n2\py-mini-racer\py_mini_racer\extension\v8_build.py", line 179, in build_v8
        ensure_v8_src()
      File "C:\Users\jared\AppData\Local\Temp\pip-install-bht625n2\py-mini-racer\py_mini_racer\extension\v8_build.py", line 65, in ensure_v8_src
        update_v8(path)
      File "C:\Users\jared\AppData\Local\Temp\pip-install-bht625n2\py-mini-racer\py_mini_racer\extension\v8_build.py", line 82, in update_v8
        call("gclient fetch")
      File "C:\Users\jared\AppData\Local\Temp\pip-install-bht625n2\py-mini-racer\py_mini_racer\extension\v8_build.py", line 38, in call
        return subprocess.check_call(cmd, shell=True, env=current_env)
      File "C:\Users\jared\Anaconda3\lib\subprocess.py", line 347, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command 'gclient fetch' returned non-zero exit status 1.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\jared\AppData\Local\Temp\pip-install-bht625n2\py-mini-racer\setup.py", line 250, in <module>
        'build_v8': MiniRacerBuildV8,
      File "C:\Users\jared\Anaconda3\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\jared\Anaconda3\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\jared\Anaconda3\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Users\jared\Anaconda3\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\jared\Anaconda3\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\Users\jared\Anaconda3\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "C:\Users\jared\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\jared\Anaconda3\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\jared\Anaconda3\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "C:\Users\jared\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\jared\Anaconda3\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\jared\Anaconda3\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
        _build_ext.run(self)
      File "C:\Users\jared\Anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "C:\Users\jared\Anaconda3\lib\distutils\command\build_ext.py", line 340, in run
        self.build_extensions()
      File "C:\Users\jared\Anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 194, in build_extensions
        self.build_extension(ext)
      File "C:\Users\jared\AppData\Local\Temp\pip-install-bht625n2\py-mini-racer\setup.py", line 180, in build_extension
        raise Exception(err_msg % repr(e))
    Exception: py_mini_racer failed to build, ensure you have an up-to-date pip (>= 8.1) to use the wheel instead
                To update pip: 'pip install -U pip'
                See also: https://github.com/sqreen/PyMiniRacer#binary-builds-availability

                Original error: CalledProcessError(1, 'gclient fetch')
    building v8
    ----------------------------------------
ERROR: Command "'C:\Users\jared\Anaconda3\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\jared\\AppData\\Local\\Temp\\pip-install-bht625n2\\py-mini-racer\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\jared\AppData\Local\Temp\pip-record-bfc_szuj\install-record.txt' --single-version-externally-managed --compile" failed with error code 1 in C:\Users\jared\AppData\Local\Temp\pip-install-bht625n2\py-mini-racer\

### System configuration
**pip version**: pip 19.1.1 from C:\Users\jared\Anaconda3\lib\site-packages\pip (python 3.7)
**setuptools version**: setuptools-42.0.2
**Python version**: 3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]

**Comment by nizox** [comment]
The last beta version of PyMiniRacer should have a working support for Windows (https://pypi.org/project/py-mini-racer/0.2.0b2/). You can install it with the following command:
```
pip install --pre py-mini-racer
```

**Comment by jaredliw** [comment]
Thanks! It works!
