### ISSUE TITLE
Fails to build docker container

### ISSUE THREAD

**Issue by alexpdr** [sqreen/PyMiniRacer#94]
### Steps to reproduce
1. Attempt to create any docker container with the given requirements.txt
2. Load Python3 requirements in before_script
```yaml
before_script:
  - pip3 install -r requirements.txt
```

requirements.txt
```txt
flake8==3.7.9
sqreen==1.17.1
yagmail==0.11.224
```
### Expected behavior
Dependencies are installed successfully.

### Actual behavior
```
386 Installing collected packages: entrypoints, pyflakes, mccabe, pycodestyle, flake8, py-mini-racer, sq-native, sqreen, yagmail
387     Running setup.py install for py-mini-racer: started
388     Running setup.py install for py-mini-racer: finished with status 'error'
389     ERROR: Command errored out with exit status 1:
390      command: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-930p24mh/py-mini-racer/setup.py'"'"'; __file__='"'"'/tmp/pip-install-930p24mh/py-mini-racer/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-svmr4a41/install-record.txt --single-version-externally-managed --compile --home=/tmp/pip-target-ofk9bhjl
391          cwd: /tmp/pip-install-930p24mh/py-mini-racer/
392     Complete output (104 lines):
393     running install
394     running build
395     running build_py
396     creating build
397     creating build/lib.linux-x86_64-3.8
398     creating build/lib.linux-x86_64-3.8/py_mini_racer
399     copying py_mini_racer/__init__.py -> build/lib.linux-x86_64-3.8/py_mini_racer
400     copying py_mini_racer/py_mini_racer.py -> build/lib.linux-x86_64-3.8/py_mini_racer
401     creating build/lib.linux-x86_64-3.8/py_mini_racer/extension
402     copying py_mini_racer/extension/__init__.py -> build/lib.linux-x86_64-3.8/py_mini_racer/extension
403     copying py_mini_racer/extension/v8_build.py -> build/lib.linux-x86_64-3.8/py_mini_racer/extension
404     running egg_info
405     writing py_mini_racer.egg-info/PKG-INFO
406     writing dependency_links to py_mini_racer.egg-info/dependency_links.txt
407     writing top-level names to py_mini_racer.egg-info/top_level.txt
408     reading manifest file 'py_mini_racer.egg-info/SOURCES.txt'
409     reading manifest template 'MANIFEST.in'
410     warning: no previously-included files matching '__pycache__' found under directory '*'
411     warning: no previously-included files matching '*.py[co]' found under directory '*'
412     writing manifest file 'py_mini_racer.egg-info/SOURCES.txt'
413     copying py_mini_racer/extension/mini_racer_extension.cc -> build/lib.linux-x86_64-3.8/py_mini_racer/extension
414     running build_ext
415     running build_v8
416     cloning depot tools submodule
417     Traceback (most recent call last):
418       File "/tmp/pip-install-930p24mh/py-mini-racer/setup.py", line 161, in build_extension
419         self.run_command('build_v8')
420       File "/usr/local/lib/python3.8/distutils/cmd.py", line 313, in run_command
421         self.distribution.run_command(command)
422       File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
423         cmd_obj.run()
424       File "/tmp/pip-install-930p24mh/py-mini-racer/setup.py", line 203, in run
425         check_call(['git', 'init'])
426       File "/usr/local/lib/python3.8/subprocess.py", line 359, in check_call
427         retcode = call(*popenargs, **kwargs)
428       File "/usr/local/lib/python3.8/subprocess.py", line 340, in call
429         with Popen(*popenargs, **kwargs) as p:
430       File "/usr/local/lib/python3.8/subprocess.py", line 854, in __init__
431         self._execute_child(args, executable, preexec_fn, close_fds,
432       File "/usr/local/lib/python3.8/subprocess.py", line 1702, in _execute_child
433         raise child_exception_type(errno_num, err_msg, err_filename)
434     FileNotFoundError: [Errno 2] No such file or directory: 'git'
435     Traceback (most recent call last):
436       File "/tmp/pip-install-930p24mh/py-mini-racer/setup.py", line 161, in build_extension
437         self.run_command('build_v8')
438       File "/usr/local/lib/python3.8/distutils/cmd.py", line 313, in run_command
439         self.distribution.run_command(command)
440       File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
441         cmd_obj.run()
442       File "/tmp/pip-install-930p24mh/py-mini-racer/setup.py", line 203, in run
443         check_call(['git', 'init'])
444       File "/usr/local/lib/python3.8/subprocess.py", line 359, in check_call
445         retcode = call(*popenargs, **kwargs)
446       File "/usr/local/lib/python3.8/subprocess.py", line 340, in call
447         with Popen(*popenargs, **kwargs) as p:
448       File "/usr/local/lib/python3.8/subprocess.py", line 854, in __init__
449         self._execute_child(args, executable, preexec_fn, close_fds,
450       File "/usr/local/lib/python3.8/subprocess.py", line 1702, in _execute_child
451         raise child_exception_type(errno_num, err_msg, err_filename)
452     FileNotFoundError: [Errno 2] No such file or directory: 'git'
453     
454     During handling of the above exception, another exception occurred:
455     
456     Traceback (most recent call last):
457       File "<string>", line 1, in <module>
458       File "/tmp/pip-install-930p24mh/py-mini-racer/setup.py", line 212, in <module>
459         setup(
460       File "/usr/local/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
461         return distutils.core.setup(**attrs)
462       File "/usr/local/lib/python3.8/distutils/core.py", line 148, in setup
463         dist.run_commands()
464       File "/usr/local/lib/python3.8/distutils/dist.py", line 966, in run_commands
465         self.run_command(cmd)
466       File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
467         cmd_obj.run()
468       File "/usr/local/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
469         return orig.install.run(self)
470       File "/usr/local/lib/python3.8/distutils/command/install.py", line 545, in run
471         self.run_command('build')
472       File "/usr/local/lib/python3.8/distutils/cmd.py", line 313, in run_command
473         self.distribution.run_command(command)
474       File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
475         cmd_obj.run()
476       File "/usr/local/lib/python3.8/distutils/command/build.py", line 135, in run
477         self.run_command(cmd_name)
478       File "/usr/local/lib/python3.8/distutils/cmd.py", line 313, in run_command
479         self.distribution.run_command(command)
480       File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
481         cmd_obj.run()
482       File "/usr/local/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 84, in run
483         _build_ext.run(self)
484       File "/usr/local/lib/python3.8/distutils/command/build_ext.py", line 340, in run
485         self.build_extensions()
486       File "/usr/local/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
487         self._build_extensions_serial()
488       File "/usr/local/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
489         self.build_extension(ext)
490       File "/tmp/pip-install-930p24mh/py-mini-racer/setup.py", line 180, in build_extension
491         raise Exception(err_msg % repr(e))
492     Exception: py_mini_racer failed to build, ensure you have an up-to-date pip (>= 8.1) to use the wheel instead
493                 To update pip: 'pip install -U pip'
494                 See also: https://github.com/sqreen/PyMiniRacer#binary-builds-availability
495     
496                 Original error: FileNotFoundError(2, 'No such file or directory')
497     ----------------------------------------
498 ERROR: Command errored out with exit status 1: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-930p24mh/py-mini-racer/setup.py'"'"'; __file__='"'"'/tmp/pip-install-930p24mh/py-mini-racer/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-svmr4a41/install-record.txt --single-version-externally-managed --compile --home=/tmp/pip-target-ofk9bhjl Check the logs for full command output.
499 The command '/bin/sh -c pip install -r requirements.txt --target=/home/app/python' returned a non-zero code: 1
```

### System configuration
Whatever version `sqreen==1.17.1` pulls in.

**Python version**:
python:3-alpine (from docker)

**Comment by alexpdr** [comment]
I can also add that git is installed with `--no-cache`... It looks like it expects a git folder but without the default hidden prefix? (.git)

**Comment by alexpdr** [comment]
Same error occurs locally as well. Attempting to build docker image and it immediately breaks with the exact same error message.

**Comment by alexpdr** [comment]
So I added the required sub-dependencies of git and bash and was provided with a new error message.
Now it fails because it tries to use python 2.7 (which reached EOL 01 January 2020)

```
Building wheels for collected packages: sq-native, py-mini-racer
  Building wheel for sq-native (setup.py): started
  Building wheel for sq-native (setup.py): finished with status 'done'
  Created wheel for sq-native: filename=sq_native-0.5.0.0.2-cp38-none-any.whl size=6713 sha256=709bbe7d115d2aefd4d4aae59065b15a3fd1386a3fd0a7e2e465d76957ef4655
  Stored in directory: /home/app/.cache/pip/wheels/c8/2c/b9/317937b969e7735494b7a80bd59d2e5855294487abbc87b2db
  Building wheel for py-mini-racer (setup.py): started
  Building wheel for py-mini-racer (setup.py): still running...
  Building wheel for py-mini-racer (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-1nt_sj0i/py-mini-racer/setup.py'"'"'; __file__='"'"'/tmp/pip-install-1nt_sj0i/py-mini-racer/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-7sxmfefy --python-tag cp38
       cwd: /tmp/pip-install-1nt_sj0i/py-mini-racer/
  Complete output (139 lines):
  running bdist_wheel
  The [wheel] section is deprecated. Use [bdist_wheel] instead.
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.8
  creating build/lib.linux-x86_64-3.8/py_mini_racer
  copying py_mini_racer/__init__.py -> build/lib.linux-x86_64-3.8/py_mini_racer
  copying py_mini_racer/py_mini_racer.py -> build/lib.linux-x86_64-3.8/py_mini_racer
  creating build/lib.linux-x86_64-3.8/py_mini_racer/extension
  copying py_mini_racer/extension/v8_build.py -> build/lib.linux-x86_64-3.8/py_mini_racer/extension
  copying py_mini_racer/extension/__init__.py -> build/lib.linux-x86_64-3.8/py_mini_racer/extension
  running egg_info
  writing py_mini_racer.egg-info/PKG-INFO
  writing dependency_links to py_mini_racer.egg-info/dependency_links.txt
  writing top-level names to py_mini_racer.egg-info/top_level.txt
  reading manifest file 'py_mini_racer.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files matching '__pycache__' found under directory '*'
  warning: no previously-included files matching '*.py[co]' found under directory '*'
  writing manifest file 'py_mini_racer.egg-info/SOURCES.txt'
  copying py_mini_racer/extension/mini_racer_extension.cc -> build/lib.linux-x86_64-3.8/py_mini_racer/extension
  running build_ext
  running build_v8
  cloning depot tools submodule
  Initialized empty Git repository in /tmp/pip-install-1nt_sj0i/py-mini-racer/.git/
  Cloning into 'vendor/depot_tools'...
  building v8
  DEBUG:py_mini_racer.extension.v8_build:Calling: 'fetch v8' from working directory /tmp/pip-install-1nt_sj0i/py-mini-racer/py_mini_racer/extension/v8
  [E2020-01-06T10:25:33.273462Z 32 0 annotate.go:241] goroutine 1:
  [E2020-01-06T10:25:33.273480Z 32 0 annotate.go:241] #0 go.chromium.org/luci/vpython/python/find.go:93 - python.Find()
  [E2020-01-06T10:25:33.273486Z 32 0 annotate.go:241]   annotation #0:
  [E2020-01-06T10:25:33.273491Z 32 0 annotate.go:241]     reason: no Python found
  [E2020-01-06T10:25:33.273495Z 32 0 annotate.go:241]   annotation #1:
  [E2020-01-06T10:25:33.273499Z 32 0 annotate.go:241]     reason: could not find appropriate executable for: "python2.7"
  [E2020-01-06T10:25:33.273503Z 32 0 annotate.go:241]   annotation #2:
  [E2020-01-06T10:25:33.273508Z 32 0 annotate.go:241]     reason: could not find target in system
  [E2020-01-06T10:25:33.273512Z 32 0 annotate.go:241]     internal reason: target(python2.7)/dirs([/tmp/pip-install-1nt_sj0i/py-mini-racer/vendor/depot_tools /usr/local/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /home/app/.local/bin /home/app/python/bin/ /tmp/pip-install-1nt_sj0i/py-mini-racer/vendor/depot_tools])
  [E2020-01-06T10:25:33.273517Z 32 0 annotate.go:241]
  [E2020-01-06T10:25:33.273521Z 32 0 annotate.go:241] #1 go.chromium.org/luci/vpython/venv/config.go:271 - venv.(*Config).resolvePythonInterpreter()
  [E2020-01-06T10:25:33.273526Z 32 0 annotate.go:241]   reason: could not find Python for: 2.7.0
  [E2020-01-06T10:25:33.273530Z 32 0 annotate.go:241]
  [E2020-01-06T10:25:33.273534Z 32 0 annotate.go:241] #2 go.chromium.org/luci/vpython/venv/config.go:186 - venv.(*Config).makeEnv()
  [E2020-01-06T10:25:33.273539Z 32 0 annotate.go:241]   reason: failed to resolve system Python interpreter
  [E2020-01-06T10:25:33.273545Z 32 0 annotate.go:241]
  [E2020-01-06T10:25:33.273549Z 32 0 annotate.go:241] #3 go.chromium.org/luci/vpython/venv/venv.go:150 - venv.With()
  [E2020-01-06T10:25:33.273554Z 32 0 annotate.go:241]   reason: failed to initialize empty probe environment
  [E2020-01-06T10:25:33.273558Z 32 0 annotate.go:241]
  [E2020-01-06T10:25:33.273562Z 32 0 annotate.go:241] #4 go.chromium.org/luci/vpython/run.go:62 - vpython.Run()
  [E2020-01-06T10:25:33.273567Z 32 0 annotate.go:241] #5 go.chromium.org/luci/vpython/application/application.go:312 - application.(*application).mainImpl()
  [E2020-01-06T10:25:33.273571Z 32 0 annotate.go:241] #6 go.chromium.org/luci/vpython/application/application.go:397 - application.(*Config).Main.func1()
  [E2020-01-06T10:25:33.273575Z 32 0 annotate.go:241] #7 go.chromium.org/luci/vpython/application/support.go:46 - application.run()
  [E2020-01-06T10:25:33.273579Z 32 0 annotate.go:241] #8 go.chromium.org/luci/vpython/application/application.go:396 - application.(*Config).Main()
  [E2020-01-06T10:25:33.273583Z 32 0 annotate.go:241] #9 vpython/main.go:105 - main.mainImpl()
  [E2020-01-06T10:25:33.273587Z 32 0 annotate.go:241] #10 vpython/main.go:111 - main.main()
  [E2020-01-06T10:25:33.273591Z 32 0 annotate.go:241] #11 runtime/proc.go:203 - runtime.main()
  [E2020-01-06T10:25:33.273595Z 32 0 annotate.go:241] #12 runtime/asm_amd64.s:1357 - runtime.goexit()
  Traceback (most recent call last):
    File "/tmp/pip-install-1nt_sj0i/py-mini-racer/setup.py", line 161, in build_extension
      self.run_command('build_v8')
    File "/usr/local/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-1nt_sj0i/py-mini-racer/setup.py", line 208, in run
      build_v8()
    File "/tmp/pip-install-1nt_sj0i/py-mini-racer/py_mini_racer/extension/v8_build.py", line 179, in build_v8
      ensure_v8_src()
    File "/tmp/pip-install-1nt_sj0i/py-mini-racer/py_mini_racer/extension/v8_build.py", line 63, in ensure_v8_src
      fetch_v8(path)
    File "/tmp/pip-install-1nt_sj0i/py-mini-racer/py_mini_racer/extension/v8_build.py", line 75, in fetch_v8
      call("fetch v8")
    File "/tmp/pip-install-1nt_sj0i/py-mini-racer/py_mini_racer/extension/v8_build.py", line 38, in call
      return subprocess.check_call(cmd, shell=True, env=current_env)
    File "/usr/local/lib/python3.8/subprocess.py", line 364, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command 'fetch v8' returned non-zero exit status 1.
  Traceback (most recent call last):
    File "/tmp/pip-install-1nt_sj0i/py-mini-racer/setup.py", line 161, in build_extension
      self.run_command('build_v8')
    File "/usr/local/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-1nt_sj0i/py-mini-racer/setup.py", line 208, in run
      build_v8()
    File "/tmp/pip-install-1nt_sj0i/py-mini-racer/py_mini_racer/extension/v8_build.py", line 179, in build_v8
      ensure_v8_src()
    File "/tmp/pip-install-1nt_sj0i/py-mini-racer/py_mini_racer/extension/v8_build.py", line 63, in ensure_v8_src
      fetch_v8(path)
    File "/tmp/pip-install-1nt_sj0i/py-mini-racer/py_mini_racer/extension/v8_build.py", line 75, in fetch_v8
      call("fetch v8")
    File "/tmp/pip-install-1nt_sj0i/py-mini-racer/py_mini_racer/extension/v8_build.py", line 38, in call
      return subprocess.check_call(cmd, shell=True, env=current_env)
    File "/usr/local/lib/python3.8/subprocess.py", line 364, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command 'fetch v8' returned non-zero exit status 1.
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-1nt_sj0i/py-mini-racer/setup.py", line 212, in <module>
      setup(
    File "/usr/local/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "/usr/local/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.8/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/local/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 84, in run
      _build_ext.run(self)
    File "/usr/local/lib/python3.8/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "/usr/local/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
      self._build_extensions_serial()
    File "/usr/local/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
      self.build_extension(ext)
    File "/tmp/pip-install-1nt_sj0i/py-mini-racer/setup.py", line 180, in build_extension
      raise Exception(err_msg % repr(e))
  Exception: py_mini_racer failed to build, ensure you have an up-to-date pip (>= 8.1) to use the wheel instead
              To update pip: 'pip install -U pip'
              See also: https://github.com/sqreen/PyMiniRacer#binary-builds-availability
  
              Original error: CalledProcessError(1, 'fetch v8')
  ----------------------------------------
  ERROR: Failed building wheel for py-mini-racer
  Running setup.py clean for py-mini-racer
Successfully built sq-native
Failed to build py-mini-racer
Installing collected packages: mccabe, pycodestyle, entrypoints, pyflakes, flake8, sq-native, py-mini-racer, sqreen, yagmail
    Running setup.py install for py-mini-racer: started
    Running setup.py install for py-mini-racer: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-1nt_sj0i/py-mini-racer/setup.py'"'"'; __file__='"'"'/tmp/pip-install-1nt_sj0i/py-mini-racer/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-s2rkxdif/install-record.txt --single-version-externally-managed --compile --home=/tmp/pip-target-ijw14bvg
         cwd: /tmp/pip-install-1nt_sj0i/py-mini-racer/
    Complete output (114 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.8
    creating build/lib.linux-x86_64-3.8/py_mini_racer
    copying py_mini_racer/__init__.py -> build/lib.linux-x86_64-3.8/py_mini_racer
    copying py_mini_racer/py_mini_racer.py -> build/lib.linux-x86_64-3.8/py_mini_racer
    creating build/lib.linux-x86_64-3.8/py_mini_racer/extension
    copying py_mini_racer/extension/v8_build.py -> build/lib.linux-x86_64-3.8/py_mini_racer/extension
    copying py_mini_racer/extension/__init__.py -> build/lib.linux-x86_64-3.8/py_mini_racer/extension
    running egg_info
    writing py_mini_racer.egg-info/PKG-INFO
    writing dependency_links to py_mini_racer.egg-info/dependency_links.txt
    writing top-level names to py_mini_racer.egg-info/top_level.txt
    reading manifest file 'py_mini_racer.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '__pycache__' found under directory '*'
    warning: no previously-included files matching '*.py[co]' found under directory '*'
    writing manifest file 'py_mini_racer.egg-info/SOURCES.txt'
    copying py_mini_racer/extension/mini_racer_extension.cc -> build/lib.linux-x86_64-3.8/py_mini_racer/extension
    running build_ext
    running build_v8
    building v8
    DEBUG:py_mini_racer.extension.v8_build:Calling: 'gclient fetch' from working directory /tmp/pip-install-1nt_sj0i/py-mini-racer/py_mini_racer/extension/v8
    Warning: gclient doesn't yet support Python 3 and may not work correctly.
    WARNING: Your metrics.cfg file was invalid or nonexistent. A new one will be created.
    You need to run gclient sync at least once to use 'recurse'.
    This is because .gclient_entries needs to exist and be up to date.
    Can't find .gclient_entries
    Traceback (most recent call last):
      File "/tmp/pip-install-1nt_sj0i/py-mini-racer/setup.py", line 161, in build_extension
        self.run_command('build_v8')
      File "/usr/local/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-1nt_sj0i/py-mini-racer/setup.py", line 208, in run
        build_v8()
      File "/tmp/pip-install-1nt_sj0i/py-mini-racer/py_mini_racer/extension/v8_build.py", line 179, in build_v8
        ensure_v8_src()
      File "/tmp/pip-install-1nt_sj0i/py-mini-racer/py_mini_racer/extension/v8_build.py", line 65, in ensure_v8_src
        update_v8(path)
      File "/tmp/pip-install-1nt_sj0i/py-mini-racer/py_mini_racer/extension/v8_build.py", line 82, in update_v8
        call("gclient fetch")
      File "/tmp/pip-install-1nt_sj0i/py-mini-racer/py_mini_racer/extension/v8_build.py", line 38, in call
        return subprocess.check_call(cmd, shell=True, env=current_env)
      File "/usr/local/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command 'gclient fetch' returned non-zero exit status 1.
    Traceback (most recent call last):
      File "/tmp/pip-install-1nt_sj0i/py-mini-racer/setup.py", line 161, in build_extension
        self.run_command('build_v8')
      File "/usr/local/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-1nt_sj0i/py-mini-racer/setup.py", line 208, in run
        build_v8()
      File "/tmp/pip-install-1nt_sj0i/py-mini-racer/py_mini_racer/extension/v8_build.py", line 179, in build_v8
        ensure_v8_src()
      File "/tmp/pip-install-1nt_sj0i/py-mini-racer/py_mini_racer/extension/v8_build.py", line 65, in ensure_v8_src
        update_v8(path)
      File "/tmp/pip-install-1nt_sj0i/py-mini-racer/py_mini_racer/extension/v8_build.py", line 82, in update_v8
        call("gclient fetch")
      File "/tmp/pip-install-1nt_sj0i/py-mini-racer/py_mini_racer/extension/v8_build.py", line 38, in call
        return subprocess.check_call(cmd, shell=True, env=current_env)
      File "/usr/local/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command 'gclient fetch' returned non-zero exit status 1.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-1nt_sj0i/py-mini-racer/setup.py", line 212, in <module>
        setup(
      File "/usr/local/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/lib/python3.8/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/usr/local/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.8/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/local/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 84, in run
        _build_ext.run(self)
      File "/usr/local/lib/python3.8/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/usr/local/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "/usr/local/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "/tmp/pip-install-1nt_sj0i/py-mini-racer/setup.py", line 180, in build_extension
        raise Exception(err_msg % repr(e))
    Exception: py_mini_racer failed to build, ensure you have an up-to-date pip (>= 8.1) to use the wheel instead
                To update pip: 'pip install -U pip'
                See also: https://github.com/sqreen/PyMiniRacer#binary-builds-availability
    
                Original error: CalledProcessError(1, 'gclient fetch')
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-1nt_sj0i/py-mini-racer/setup.py'"'"'; __file__='"'"'/tmp/pip-install-1nt_sj0i/py-mini-racer/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-s2rkxdif/install-record.txt --single-version-externally-managed --compile --home=/tmp/pip-target-ijw14bvg Check the logs for full command output.
The command '/bin/sh -c pip install -r requirements.txt --target=/home/app/python' returned a non-zero code: 1
[0] < Building func-sendmail done in 153.66s.
[0] Worker done.

Total build time: 153.66
Errors received during build:
- [func-sendmail] received non-zero exit code from build, error: The command '/bin/sh -c pip install -r requirements.txt --target=/home/app/python' returned a non-zero code: 1
```

**Comment by nizox** [comment]
There are special installation instructions for Alpine Linux. In fact, Alpine is not a manylinux distribution and requires dedicated wheel builds.

You should be able to install it using:
```
$ apk add libgcc
$ pip install --index-url https://download.sqreen.io/python/alpine py-mini-racer
```

**Comment by alexpdr** [comment]
Using the special version for Alpine solved the problems! Issue can be closed :)
